TableData_Datecal/Models/DataTable.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableData_Datecal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TableEntities : DbContext
    {
        public TableEntities()
            : base("name=TableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableData> TableDatas { get; set; }
    }
}

TableData_Datecal/Models/DataTable.Designer.cs
// T4 code generation is enabled for model 'C:\Users\00001244\source\repos\TableData_Datecal\TableData_Datecal\Models\DataTable.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

TableData_Datecal/Models/DataTable.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

TableData_Datecal/Models/TableData.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableData_Datecal.Models
{
    using System;
    using System.Collections.Generic;
     public partial class TableData
    {
        public int Id { get; set; }
        public string First_Date { get; set; }
        public string Second_Date { get; set; }
        public string Result { get; set; }
        public int m, d, y;
        int[] monthDay = new int[12] { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };

       public int getDifference(TableData dt1, TableData dt2)
        {
            int n1 = dt1.y * 365 + dt1.d;
            for (int i = 0; i < dt1.m - 1; i++)

                n1 = n1 + monthDay[i];
            n1 = n1 + CountLeapYear(dt1);

            int n2 = dt2.y * 365 + dt2.d;
            for (int i = 0; i < dt2.m - 1; i++)
                n2 = n2 + monthDay[i];
            n2 = n2 + CountLeapYear(dt2);
            return n2 - n1;
        }
        int CountLeapYear(TableData d)
        {
            int year = d.y;
            if (d.m <= 2)
                year--;
            return year / 4 - year / 100 + year / 400;
        }


    }
}

TableData_Datecal/Models/TableDateDiff.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TableData_Datecal.Models
{
    public class TableDateDiff
    {
       // public TableData CurretData { get; set; }
        //public List<TableData> tableData;
    }
}

TableData_Datecal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TableData_Datecal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TableData_Datecal/Controllers/Table_DatecalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TableData_Datecal.Models;

namespace TableData_Datecal.Controllers
{
    public class Table_DatecalController : Controller
    {
        // GET: Table_Datecal
        public TableEntities db = new TableEntities();
        [HttpGet]
        public ActionResult Index()
        {
            var data = db.TableDatas.ToList();
            ViewBag.displaydata = data;
            return View(data);
        }

        [HttpPost]
       // [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "First_Date,Second_Date,Result")] TableData datecal)
        {
            if (ModelState.IsValid)
            {

                string a = datecal.First_Date;

                int y1 = Convert.ToInt32(a.Split('-')[0]);
                int m1 = Convert.ToInt32(a.Split('-')[1]);
                int d1 = Convert.ToInt32(a.Split('-')[2]);
                string b = datecal.Second_Date;
                int y2 = Convert.ToInt32(b.Split('-')[0]);
                int m2 = Convert.ToInt32(b.Split('-')[1]);
                int d2 = Convert.ToInt32(b.Split('-')[2]);
                TableData dt1 = new TableData
                {
                    y = y1,
                    m = m1,
                    d = d1

                };
                TableData dt2 = new TableData
                {
                    y = y2,
                    m = m2,
                    d = d2

                };
                TableData dt = new TableData();

                int Result = dt.getDifference(dt1, dt2);

                dt.First_Date = a;
                dt.Second_Date = b;
                dt.Result = Result.ToString();
                ViewBag.Result = dt.Result;
                db.TableDatas.Add(dt);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(datecal);


        }
         

        }
       
    }

TableData_Datecal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TableData_Datecal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TableData_Datecal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TableData_Datecal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @{ 
        Html.RenderPartial("_PartialView");
    }
    <div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TableData_Datecal/Views/Shared/_PartialView.cshtml
<div style="background-color:antiquewhite">
    <div class="navbar navbar-header navbar-fixed-top nav-justified" style="background-color:aquamarine">

        <div class="container-fluid">
            <div class="navbar-header">
                @*<button type="button" class="navbar-toggle btn btn-info"data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar" style="color:aqua"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>*@
                <div class="active" style="color:blueviolet">
                    @*@Html.ActionLink("My MVC Application", "Index", "Table_Datecal", new { area = "" }, new { @class = "navbar-brand" })*@

                    <div class="container-fluid">
                    <div class="navbar-collapse collapse">
                        <div class="text-info">
                            <ul class="nav navbar-nav">

                                <li>@Html.ActionLink("Home", "Index", "Table_Datecal")</li>
                                <li>@Html.ActionLink("About", "Index", "Table_Datecal")</li>
                                <li>@Html.ActionLink("DateCal", "Index", "Table_Datecal")</li>
                            </ul>
                        </div>
                        </DIV>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TableData_Datecal/Views/Table_Datecal/Index.cshtml
@model IEnumerable<TableData_Datecal.Models.TableData>
@using TableData_Datecal.Models
@{
    ViewBag.Title = "Create";
}
@Html.Partial("_PartialView")
<div class="container-fluid">
<div class="row" style="margin-top:30px">
    <div class="col-lg-6" style="color:blue">


        @using (@Html.BeginForm("Index", "Table_Datecal", FormMethod.Post))
        {

            <table class="table table-bordered" style="background-color:gainsboro">
                <tr>
                    <td>
                        @Html.LabelFor(M => M.FirstOrDefault().First_Date)
                    </td>
                    @*<td>@Html.TextBoxFor(m => m.FirstOrDefault().First_Date)<br /></td>*@
                    <td>@Html.TextBox("First_Name"," ")<br /></td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(m => m.FirstOrDefault().Second_Date)</td>
                    <td>@*@Html.TextBoxFor(m => m.FirstOrDefault().Second_Date)<br />*@ @Html.TextBox("Second_Name"," ")</td>
                </tr> 
               @* <tr>
                        <td>@Html.LabelFor(m => m.FirstOrDefault().Result)</td>
                        <td><label>@ViewBag.Result</label></td>
                    </tr>*@
                <tr>
                    <td> <input type="submit" value="submit" name="submit" style="color:brown" size="1000" height="50" width="200" /></td>
                    <td></td>
                </tr>
            </table>
        }
    </div>
 
    <div class="col-lg-6" style="color:blueviolet">
        <div class="bg-danger">
            <table class="table table-bordered">

                <thead>
                    <tr>
                        <th>
                            Id
                        </th>

                        <th>
                            First_Date
                        </th>
                        <th>
                            Second_Date
                        </th>
                        <th>
                            Result
                        </th>


                    </tr>
                </thead>
                @foreach (var i in ViewBag.displaydata)
                {
                    <tr>
                        <td>@i.Id</td>
                        <td>@i.First_Date</td>
                        <td>@i.Second_Date</td>
                        <td>@i.Result</td>
                    </tr>

                }
            </table>
        </div>
    </div>
</div>
</div>